const HOME_ENDPOINT = "/";
const DASHBOARD_ENDPOINT = "/dashboard";
const DASHBOARD_CREATE_ENDPOINT = "/dashboard/create";
const DASHBOARD_CREATE_ACTİON_ENDPOINT = "/dashboard/createCard";
const DASHBOARD_DELETE_ACTİON_ENDPOINT = "/dashboard/deleteCard/";

module.exports = {
    HOME_ENDPOINT,
    DASHBOARD_ENDPOINT,
    DASHBOARD_CREATE_ENDPOINT,
    DASHBOARD_CREATE_ACTİON_ENDPOINT,
    DASHBOARD_DELETE_ACTİON_ENDPOINT
};